### ISSUE TITLE
Welcome Video is not available 

### ISSUE THREAD

**Issue by floralan** [forcedotcom/code-builder-feedback#120]
**Describe the bug**
I can't play Welcome Video on Code Builder Dashboard.

**To Reproduce**
1. Go to 'Code Builder Dashboard'
2. Click on 'Watch Welcome Video'
3. Click on the video

**Expected behavior**
Playing a welcome video

**Screenshots**
<img width="419" alt="image" src="https://user-images.githubusercontent.com/42667832/161855169-0c3b9e45-30ff-42ce-a692-18986f2c7460.png">
No response and not seeing the video.

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser: chrome
 - Version: 11.6.5

**Comment by jgellin-sf** [comment]
The video is not currently a thing anymore. This will be reflected in the next code builder image build.
