### ISSUE TITLE
Can't run LWC tests, and can't install sfdx-lwc-jest easily

### ISSUE THREAD

**Issue by randi274** [forcedotcom/code-builder-feedback#124]
**Describe the bug**
I tried to run an LWC test, but got an error that sfdx-lwc-jest was not installed.

**To Reproduce**
1. Try to run an LWC test from the Test tab
2. See the error
3. Attempt to run the yarn command to install from the docs: `yarn add -D @salesforce/sfdx-lwc-jest`
4. See error that yarn is not installed either 🙀

**Expected behavior**
I would expect sfdx-lwc-jest to be pre-installed. Alternatively, I'd like more help being able to install that for code builder rather than going to the extensions documentation.

**Screenshots**
![Screen Shot 2022-04-05 at 5 33 32 PM](https://user-images.githubusercontent.com/9795193/161856163-4d888b27-609c-466c-be39-d49e18029acd.png)

![Screen Shot 2022-04-05 at 5 34 19 PM](https://user-images.githubusercontent.com/9795193/161856329-0567c392-fa41-435c-b369-c07b3353dbf4.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: chrome, latest

**Comment by jgellin-sf** [comment]
GUS Ref: W-10981837
