### ISSUE TITLE
There needs to be a unilateral way to resolve IP Restrictions for this Product

### ISSUE THREAD

**Issue by DebanjanBasuNasd** [forcedotcom/code-builder-feedback#196]
At the Moment whenever you login from vpn or any other network there are ip restirctions imposed . There should be a unilateral way of resolving this rather than populating and editing under profiles and Login ip ranges

**Comment by ryanbrainard** [comment]
See https://github.com/forcedotcom/code-builder-feedback/issues/235#issuecomment-1785508011
