### ISSUE TITLE
Please make Code Builder Generally Available (GA)

### ISSUE THREAD

**Issue by pgonzaleznetwork** [forcedotcom/code-builder-feedback#216]
**What is your role?**

Salesforce Architect

**What do you normally work on when building on the Salesforce Platform?**

CI/CD Pipelines

**What tools do you use today to develop on the Salesforce Platform?**

Salesforce CLI and VS Code

**How do you see Code Builder fitting into your current workflow? Will it replace any tools you are currently using?**

It can be a game changer for admins, read below

**General feedback**

Hi Code Builder team,

I'm a Salesforce Architect specializing in CI/CD solutions, and I was doing research on how to create a "Git for Admins" training course.

I came across Code Builder and was blown away by how easy it is to spin up an environment ready with SFDX and Git. 

One of the main reasons Admins haven't adopted Git is because of the hassle of downloading VS Code, Git, Salesforce CLI, etc.; many of them run into errors that are hard to resolve or need IT support.

Code Builder can potentially democratize SFDX and Git for anyone, regardless of technical knowledge.

I'm convinced that once Code Builder is GA (Generally Available), we'll finally be able to teach admins how to use Git and SFDX in no time. It really has the potential to be one of the most impactful innovations in a long time.

So, I'm here to tell you to please make this GA as soon as possible. The community desperately needs this, and you have build an amazing product so far.

#GAPlease

**Comment by IdoZakk** [comment]
#GAPlease

**Comment by elchacha** [comment]
#GAPlease

**Comment by tamtamirr** [comment]
#GAPlease

**Comment by guykr** [comment]
#GAPlease

**Comment by guyhamo** [comment]
#GAPlease

**Comment by geymed** [comment]
#GAPlease

**Comment by Uri-Bar** [comment]
#GAPlease

**Comment by austinmyer** [comment]
#GAPlease

**Comment by amitgoldarb** [comment]
#GAPlease

**Comment by vishalshuklag** [comment]
#GAPlease

**Comment by tsprojects06** [comment]
#GAPlease

**Comment by jdschleicher** [comment]
@GAPlease

we have a large group working on government machines and it can be challenging and timely to get support for admin access in adjusting system environment variables.

It creates so much friction to begin with it exponentially and needlessly adds to the overwhelm of someone first learning the tools

**Comment by JohnBorgen** [comment]
This can be pivotal to my growth and the growth of others in this space. And the time is now. Tech is in a state of turmoil. Tools like this allow people to do so much more with their career.

#GAPlease

**Comment by jfryman** [comment]
Hi folks! My name is James, and I'm one of the engineers working on this project. I just happen to be on-call this week looking for various support issues or feature requests to address, so it's always great to run into something that's slightly off the beaten path.

First off, thanks so much for the kind words! I've shared this thread with the rest of the team also working on this project. It's actually quite great to hear how this is helping you in your daily lives, and even greater to see the outpouring of support from various folks who have used the product.

I can assure you we're hard at work trying to put the finishing touches on this product so that it meets all of the Trust requirements that you've come to expect from other Salesforce offerings. While I'd love to give an exact date of when we'll GA, I can assure you this is the path we're on and we're laser focused to get this out the door for even more folks to consume and enjoy.

I'd selfishly love to see even more posts with the #GAPlease tag, as it is quite motivating. So, please keep them coming. We're on the path to get this out to y'all as soon as we can. 

#OnTheRoadToGA

**Comment by theotherkimdavis** [comment]
#GAPlease

**Comment by chickman-doordash** [comment]
#GAPlease

**Comment by donapeqo** [comment]
GA Please!

**Comment by smitts001** [comment]
GA Please!. Would help us!

**Comment by dorsev** [comment]
#GAPlease

**Comment by itaishmida** [comment]
#GAPlease

**Comment by keplet** [comment]
#GAPlease

**Comment by joernflath** [comment]
#GAPlease

**Comment by amenesescr** [comment]
GA Please!!!!
#GAPlease

**Comment by DannyGelf** [comment]
Yes! I join the #217 Movement

**Comment by Tamarer** [comment]
#GAPlease

**Comment by DrRachelBaker** [comment]
#GAPlease

**Comment by emailgroupie** [comment]
#GAPlease

**Comment by merguk** [comment]
#GAPlease

**Comment by jstrother** [comment]
#GAPlease

**Comment by oecoralo** [comment]
#GAPlease

**Comment by maimaichi** [comment]
#GAPlease

**Comment by murthytumuluri04** [comment]
#217

**Comment by smaddox-sf** [comment]
WOW!  Thank you All for sharing your enthusiasm for Code Builder!  I'm ecstatic to hear how this new tool will make a difference for your teams.  We're hard at work to bring you GA later this year - stay tuned for more announcements as we get closer.  Your feedback is key to shape Code Builder, so please keep it coming!

**Comment by michael-plunkett-VRTV** [comment]
#GAPlease

**Comment by wayusei** [comment]
#GAPlease I want to learn to use git as a Salesforce admin too.

**Comment by liuxiachanghong** [comment]
I’m using VS Code , Salesforce CLI and GitHub. Working Copy app from other remote devices to maintain and develop anywhere. Only one issue unsolved is I can’t push the changes to sandbox from mobile device. 
Even though I tried the codespaces in vscode.dev,  ssh key setup is only allowed from Salesforce tech support. It sounds too complicated and elaborate, there must have been SSH key access menu before in sandbox but now it’s gone.
Hope the Code Builder (GA) can solve the issue.

**Comment by rr6584** [comment]
#GAPlease

**Comment by Aman-Dhanoa** [comment]
#GAPlease
Hopefully this will be the tool that can help me cross that brigde that I have always been scared of.

**Comment by travisjlee31** [comment]
#217

**Comment by travisjlee31** [comment]
#GAPlease

**Comment by Neenahh** [comment]
#GAPlease . Thanks in advance!

**Comment by jmasl7** [comment]
#GAPlease

**Comment by busq-io** [comment]
#GAPlease, thank you very much!

**Comment by cmarie-bel** [comment]
#GAPlease this is a crucial component to my learning process. Let's knock down this barrier and to reduce this knowledge gap and improve employability prospects!

**Comment by navkn** [comment]
#217

**Comment by Jbodhe** [comment]
#217

**Comment by Jbodhe** [comment]
#GAPlease

**Comment by smaddox-sf** [comment]
On our path to GA, we've heard feedback that the getting started experience with Code Builder can be a bit confusing.  We're looking for your input to improve this for GA!  If you have 10 minutes to spare, check out the details below on how you can participate:

- We’re looking for Code Builder users to participate in an upcoming research study. This study is focused on the getting started experience with Code Builder. 
- The focus group will be run remotely and asynchronously, and you can participate on your own time from a computer, smartphone or tablet.
- As part of the study you will be asked to navigate 1-3 prototypes and provide feedback based on questions we'll provide. **It will take about 10 minutes**.

**If you’re interested in participating, [please sign up here](https://app.usertesting.com/panels/yawb24vj/join).**

**Comment by pgonzaleznetwork** [comment]
Hi @smaddox-sf !

I'm excited to help with feedback. I signed up to the link provided but I don't see any tests yet, is this expected?

**Comment by smaddox-sf** [comment]
@pgonzaleznetwork - Awesome!  Thank you!  Yes, that is expected right now.  This week, we're gathering sign-ups and next week, you'll receive an email with with all the info to participate.  Apologies if that was unclear in my previous post.  Thank you again for participating!  We are grateful for the feedback.

**Comment by Meglong** [comment]
Hey! I'm Meg and I'm one of the UX designers for Code Builder -- I LOVE this thread! Thank you all so much for sharing.

**@smaddox-sf above mentioned the research study we're doing. If anyone is interested in participating, there's still time to sign up [sign up](https://app.usertesting.com/panels/yawb24vj/join).**

Our team will reach out to participants next week with a sneak peak of prototypes we're considering, and way to submit some quick feedback. 

Thank you to everyone who has signed up already! Really excited to get your thoughts.

**Comment by Meglong** [comment]
@pgonzaleznetwork  (and others who signed up) yesterday you should have received the invite link to participate in the research study. If you didn't receive it, try logging into your usertesting.com account and it should be accessible from your main dashboard under 'available tests.'

**If you're not able to access the test or your usertesting account**, try signing up again using the [original signup link](https://app.usertesting.com/panels/yawb24vj/join). Once you create your account, the test should show up in your dashboard under 'available tests' after a minute or two.

It should take about 10 minutes to complete.

If you're having any issues accessing let me know - thank you so much for your time and feedback!

**Comment by pgonzaleznetwork** [comment]
@Meglong I got the notification that new tests were available, I started it, but had to exist just before actually starting it due to a situation at home. Now when I log in, I don't see any tests available.

Can you make them available for me again?

**Comment by Meglong** [comment]
@pgonzaleznetwork Yes I think so! I can send you another invite -- what is your usertesting username? Feel free to email it to me at meg [dot] long [at] salesforce [dot] com

**Comment by cmwagner** [comment]
My company's security policies do not allow me to install software on my work computer, requiring instead that I open a ticket with our HelpDesk personnel who have network admin privileges.  Installing everything (i.e., [1] Salesforce CLI, [2] Zulu OpenJDK, [3] Visual Studio Code, and [4] Salesforce Extension Pack) is quite the ordeal, and that's only after I convince them that I need these things.  And don't get me started on periodic updates.  

I'm really looking forward to Salesforce once again being the "No Software" solution where I can develop LWCs and more, all within a browser based IDE.  It looks like there may be some concern about the challenging steps required to get started on Code Builder.  Is it really more difficult than getting started with software-based VS Code?  If it is such a hurdle to set up, must we limit the Beta users in hours used or days of trial?  You know, "all that work" for so little time with the tool?

#GAPlease

**Comment by RAJA-VONTIER** [comment]
#GAPlease, 
Thank you for providing the amazing product Code Builder. It saved lot of my time and IT help desk team efforts without downloading any Software i.e. VSCode, Git, Salesforce CLI and SFDX on my laptop! Looking forward to use it without time limits.

**Comment by smaddox-sf** [comment]
Thank you again for all your excitement and willingness to share the value Code Builder brings for your team.  I'm thrilled to announce that Code Builder is now GA! https://developer.salesforce.com/blogs/2023/10/salesforce-code-builder-is-now-generally-available
