### ISSUE TITLE
Code Builder doesn't work

### ISSUE THREAD

**Issue by eddunnapollo** [forcedotcom/code-builder-feedback#233]
Getting the following error
CodeBuilder.ResourceApiResponseException

There was an error communicating with the workspace. Try again later. If you still encounter errors, contact Support and provide the error details.

**Comment by jfryman** [comment]
Hi there!

Unfortunately, [Open Beta ended earlier this month](https://trailblazers.salesforce.com/profileView?u=0053000000BfNZCAA3&_ga=2.45046884.1730973139.1696264248-1339716567.1620659864), and we are in the middle of preparing for GA launch later this month. Your environment will be unable to be accessible going forward, and once we launch GA you will be able to create a new environment.

Please stay tuned in the coming weeks for our GA announcement as well as for details of how to install the new package once released.

**Comment by eddunnapollo** [comment]
Thanks James.

Will it be free?  Will there be limits in the number of hours you can use
it?

Thanks

**Comment by smaddox-sf** [comment]
Hi @eddunnapollo - Code Builder access will be user-based and we'll include some access in CRM editions like Professional, Enterprise and Unlimited.  The admin controls which users have permission to use Code Builder.  Stay tuned next week for the GA announcement with all the details!
