### ISSUE TITLE
Update VS Code version

### ISSUE THREAD

**Issue by jragno918** [forcedotcom/code-builder-feedback#234]
**Description**
When spinning up a new environment I get an error stating that Code Builder is unable to activate the Apex Language Server due to not having the right VS Code version 

**To Reproduce**
1. Create a new environment
2. Open the terminal
3. Click the 'Problems' tab in the terminal

**Screenshot**
<img width="921" alt="Screenshot 2023-10-24 at 1 33 17 PM" src="https://github.com/forcedotcom/code-builder-feedback/assets/35947958/a33c44c3-af8f-4055-affd-f1d749e48a14">

**Desktop:**
 - OS: MacOS
 - Browser: Chrome

**Comment by smaddox-sf** [comment]
HI @jragno918 - Thanks for reporting this.  We're working on a fix.

**Comment by smaddox-sf** [comment]
Hi @jragno918 - We released a fix for this issue.  Please give it another try when you get a chance and let us know if it's resolved for you.

**Comment by jragno918** [comment]
Hi @smaddox-sf, it looks good to me. Thank you!

**Comment by smaddox-sf** [comment]
Thank you for letting us know you're unblocked!
