### ISSUE TITLE
Ability to build a Package.xml manifest file in Code Builder

### ISSUE THREAD

**Issue by LStokoe** [forcedotcom/code-builder-feedback#236]
**Is your feature request related to a problem? Please describe.**
Feature request - access to a popular extension Package.xml and ability to use the UI to pull changes into vscode. This is a 'nice to have' rather than a tool that is necessary to do our work

**Describe what you are ultimately trying to do**
We have both administrators and developers using Code builder due to frequent issues with Salesforce CLI and VSCode compatibility. Some of these engineers are used to using Package.xml to pull changes from their sandbox/scratch org, and would like to be able to use this functionality in Code Builder too, but it doesn't seem to be available

**Describe how you think Code Builder can help solve your problem or improve your work**
I'd like a familiar and intuitive tool to pull changes from a sandbox/scratch org into Code Builder

**Additional context**
We're able to build the manifest file, but without the Package UI components it can be quite tedious and taxing for junior engineers

**Comment by smaddox-sf** [comment]
Hi @LStokoe - Thanks for sharing feedback!  Is this [the extension](https://marketplace.visualstudio.com/items?itemName=VignaeshRamA.sfdx-package-xml-generator) you use to generate package.xml files?

From the ‘extensions’ view in Code Builder, you can see any extension published to [Open VSX](https://open-vsx.org/).  Open VSX is the largest public forum of VS Code extensions, but it's up to the publisher to choose whether they want to add their extension.  If this publisher adds their extension to Open VSX, you would see it listed in Code Builder.

You can learn more about [Code Builder + Open VSX in this blog post](https://developer.salesforce.com/blogs/2023/06/open-vsx-extensions-are-now-supported-in-code-builder?utm_campaign=amer_sfld&utm_content=SalesforceDevs_&utm_medium=organic_social&utm_source=twitter).

**Comment by LStokoe** [comment]
@smaddox-sf Yep that's exactly what I was referring to. Thanks so much for coming back to me, that makes perfect sense, thanks for sharing these links!
