### ISSUE TITLE
Can't load the workspace.

### ISSUE THREAD

**Issue by zix66** [forcedotcom/code-builder-feedback#238]
Hi All!

Yesterday evening especially opened Code Builder to insure that all correct and I can work.
Right now  morning getting error: Can't load the workspace. 
Something Has Gone Wrong.
More Information : Empty

And it is not first time .. none stable version!

**Comment by zix66** [comment]
Screwed down!
I prepared NEW enviroinment .. added all needed extensions .. worked a couple hours, closed  and after another couple of hours SAME ERROR !!!
![Screenshot 2023-11-15 133940](https://github.com/forcedotcom/code-builder-feedback/assets/44432865/bcf69f7b-cf93-4074-a2ba-7994828d72f2)

**Comment by jgellin-sf** [comment]
@zix66 Thanks for your feedback and the environment details. We are investigating the incident that caused startup failures for your environments in the `eu` region. All systems are now reporting healthy in that region. Please let us know if you experience any more instability.

**Comment by zix66** [comment]
@jgellin-sf Thanks for answer providing! :)
.. I think that could be additional arguments for my problem
=> I added additional extensions: "Better Align" / "Bookmarks" / re-initiate for "Prettier" (npm install , existed as extension but not active upon startup workspace init) 
=> I changed settings as: 
{
  "extensions.autoUpdate": true,
  "extensions.autoCheckUpdates": true,
  "salesforcedx-vscode-apex.java.home": "/usr/lib/jvm/java-11-openjdk-amd64",
  "workbench.startupEditor": "none",
  "security.workspace.trust.enabled": true,
  "remote.autoForwardPorts": false,
  "redhat.telemetry.enabled": false,
  "workbench.colorTheme": "Monokai",
  "editor.minimap.enabled": false,
  "workbench.iconTheme": "material-icon-theme",
  "editor.codeActionsOnSave": {
  
  },
  "editor.fontFamily": "Fira Code",
  "editor.fontLigatures": true,
  "workbench.colorCustomizations": {
    "titleBar.border": "#fc000d",
    "titleBar.activeBackground": "#024c92",
    "activityBar.background": "#000000",
    "activityBar.foreground": "#ffffff",
    "activityBar.border": "#717902",
    "activityBar.activeBackground": "#505050",
    "sideBar.foreground": "#ffffff",
    "sideBar.background": "#363636",
    "sideBarSectionHeader.background": "#020202",
    "badge.background": "#e04478",
    "breadcrumb.background": "#020202",
    "breadcrumb.foreground": "#ffffff",
    "editorLineNumber.activeForeground": "#02ff81",
    "editorLineNumber.foreground": "#027559",
    "panel.border": "#ff0000",
    "editor.fontFamily": "Fira Code",
    "editor.fontLigatures": true
  },
  "window.menuBarVisibility": "classic",
  "betterAlign.surroundSpace" : {
    "colon"      : [0, 1], // The first number specify how much space to add to the left, can be negative.
                           // The second number is how much space to the right, can be negative.
    "assignment" : [1, 1], // The same as above.
    "arrow"      : [1, 1], // The same as above.
    "comment"    : 0       // Special how much space to add between the trailing comment and the code.
                           // If this value is negative, it means don't align the trailing comment.
  }
}

**Comment by jgellin-sf** [comment]
Thanks for posting your settings. Does your `settings.json` actually include those `//` comments? As part of image startup we merge user overrides with our base settings and this may be causing the startup problem.

**Comment by zix66** [comment]
comments inside settings .. yes

**Comment by jgellin-sf** [comment]
@zix66 
Our current startup script that merges settings is not able to handle those comments. I have issued a bug, and fix should both support settings with comments and make this part of the startup resilient to errors in the future. 

If it is possible for you to delete those comments temporarily, we suspect that will work around this re-start problem. 

We will update this issue when the bug is fixed.

**Comment by zix66** [comment]
@jgellin-sf Thanks! Another one remark from me :)

While standard Code Builder init process, after Org is connected successfully next step to bring metadata within **OrgBrowser** - refresh & download to get it into 'local' source .. I passed let's say 5-6 Code Builder initializations and ALWAYS OrgBrowser was INACTIVE (in same session) ..  so I was forced to REFRESH chrome and only after thjat OrgBrowser was activate to work with it!

**Comment by zix66** [comment]
@jgellin-sf 
Another one issue that I faced.
I connect Sandbox - all correct up to the end. After that I connect Production .. authorization succeed - I see production 'label' on bottom panel. I updated one class some classes (actually I meant to do combined deployment direct into Prod to delete some items) and I noticed that my change reflected in Sandbox despite I see against Prod :)

**Comment by jfryman** [comment]
Hi there.

Today we released a new set of fixes that addresses this reported behavior. Comments unfortunately will still be removed, but customizations made by our users will not cause a failure in loading.
