### ISSUE TITLE
Code Builder Start up failure

### ISSUE THREAD

**Issue by brountre** [forcedotcom/code-builder-feedback#244]
Not able to start code builder.

Steps to reproduce on my end:

1. Launch Code Builder
2. Screen shows
![image](https://github.com/forcedotcom/code-builder-feedback/assets/1190978/a7658e4a-2927-4965-b543-23beef4caefd)
It refreshes the page through this screen like 20 times or so.  
Then eventually it states:
{"statusCode":429,"error":"Too Many Requests","message":"Rate limit exceeded"}

**Comment by brountre** [comment]
I've cleared my cache & History.  I've also rebooted my computer, nothing seems to change this.  Any ideas what I can do to resolve this (Without having to start fresh)?

**Comment by jonnyhork** [comment]
@brountre Thanks for reporting the issue, sorry you are having problems getting to your environment. It sounds like this is an existing environment you're trying to access, is that right? Do you happen to know the URL of the Code Builder environment? Or your org domain, org ID or user ID?

**Comment by brountre** [comment]
@jonnyhork - It appears to be resolved now.  Not sure what happened, but it is now working.

**Comment by jonnyhork** [comment]
Cool, glad I could help ;)
